// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	jwtsecret: string;
	totpsecret: string;
	siteurl: string;
	pushurl: string;
	DB: D1Database;
}
